package com.bdcom.itester.lib;

import java.io.Serializable;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2013-6-24 <br>
 * Auto-Generated by eclipse Kepler <br>
 */

public class CaptureResult extends ConnectStatus implements Serializable {

    private static final long serialVersionUID = 6464255106054514804L;

    private String frames;

	public String getFrames() {
		return frames;
	}

	public void setFrames(String frames) {
		this.frames = frames;
	}
	
}
