package com.bdcom.itester.lib;

import java.io.Serializable;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2013-6-24 <br>
 * Auto-Generated by eclipse Kepler <br>
 */

public class ChassisInfo implements Serializable {

    private static final long serialVersionUID = -6257405779192851843L;

    private int chassisType;
	
	private int cardNum;
	
	private String description;

    private boolean connected;

    public boolean isConnected() {
        return connected;
    }

    public void setConnected(boolean connected) {
        this.connected = connected;
    }

	public int getChassisType() {
		return chassisType;
	}

	public void setChassisType(int chassisType) {
		this.chassisType = chassisType;
	}

	public int getCardNum() {
		return cardNum;
	}

	public void setCardNum(int cardNum) {
		this.cardNum = cardNum;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
}
