package com.bdcom.itester.lib;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2013-6-24 <br>
 * Auto-Generated by eclipse Kepler <br>
 */

public class ChassisInfo extends ConnectStatus {

	private int chassisType;
	
	private int cardNum;
	
	private String description;

	public int getChassisType() {
		return chassisType;
	}

	public void setChassisType(int chassisType) {
		this.chassisType = chassisType;
	}

	public int getCardNum() {
		return cardNum;
	}

	public void setCardNum(int cardNum) {
		this.cardNum = cardNum;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
}
