package com.bdcom.itester.lib;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2013-6-24 <br>
 * Auto-Generated by eclipse Kepler <br>
 */

public class LinkStatus extends ConnectStatus {
	
	private boolean linked;
	
	public boolean isLinked() {
		return linked;
	}

	public void setLinked(boolean linked) {
		this.linked = linked;
	}

}
