package com.bdcom.itester.lib;

import java.io.Serializable;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2013-6-25 <br>
 * Auto-Generated by eclipse Kepler <br>
 */

public class PortStats extends LinkStatus implements Serializable {

    private static final long serialVersionUID = 7048552974621794245L;

    private int[] stats;

	public int[] getStats() {
		return stats;
	}

	public void setStats(int[] stats) {
		this.stats = stats;
	}
	
}
