package com.bdcom.itester.lib;

import java.io.Serializable;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2013-6-25 <br>
 * Auto-Generated by eclipse Kepler <br>
 */

public class PortStats implements Serializable {

    private static final long serialVersionUID = 7048552974621794245L;

    private long[] stats;

    private boolean connected;

    public boolean isConnected() {
        return connected;
    }

    public void setConnected(boolean connected) {
        this.connected = connected;
    }

	public long[] getStats() {
		return stats;
	}

	public void setStats(long[] stats) {
		this.stats = stats;
	}
	
}
