package com.bdcom.itester.lib;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2013-6-24 <br>
 * Auto-Generated by eclipse Kepler <br>
 */

public class StreamInfo extends ConnectStatus {
	
	private long packetCount;
	
	public long getPacketCount() {
		return packetCount;
	}

	public void setPacketCount(long packetCount) {
		this.packetCount = packetCount;
	} 
	
}
