package com.bdcom.itester.lib;

import java.io.Serializable;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2013-6-24 <br>
 * Auto-Generated by eclipse Kepler <br>
 */

public class WorkInfo implements Serializable {

    private static final long serialVersionUID = 298862830553064301L;

    public boolean workNow;

    private boolean connected;

    public boolean isConnected() {
        return connected;
    }

    public void setConnected(boolean connected) {
        this.connected = connected;
    }

	public boolean isWorkNow() {
		return workNow;
	}

	public void setWorkNow(boolean workNow) {
		this.workNow = workNow;
	}

}
