package com.bdcom.itester.lib;

import java.io.Serializable;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2013-6-24 <br>
 * Auto-Generated by eclipse Kepler <br>
 */

public class WorkInfo extends ConnectStatus implements Serializable {

    private static final long serialVersionUID = 298862830553064301L;

    public boolean workNow;

	public boolean isWorkNow() {
		return workNow;
	}

	public void setWorkNow(boolean workNow) {
		this.workNow = workNow;
	}

}
