package com.bdcom.biz.script;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2012-11-26 <br>
 * Auto-Generated by eclipse Juno <br>
 */

public interface ScriptXmlConfConstants {
	
	public static final String RAW_DATA_PATH = "rawDataPath";
	
	public static final String DEFAULT_IPT_PATH = "globalIptPath";
	
	public static final String _CRT_SESSIONS = "crtSessions";
	
	public static final String _CRT_SESSION = "crtSession";
	
	public static final String _INTERPRETERS = "interpreters";
	
	public static final String _INTERPRETER = "interpreter";
	
	public static final String _NAME = "name";
	
	public static final String _SCRIPTS = "scripts";
	
	public static final String _SCRIPT = "script";
	
	public static final String _SERIAL = "serial";
	
	public static final String _PATH = "path";
	
	public static final String _BEGIN_INDEX = "beginIndex";
	
	public static final String _SETTING = "setting";
	
	public static final String _INTERACTOR = "interactor";
	
	public static final String _INPUT_ACTOR = "input";
	
	public static final String _SWITCH_ACTOR = "switch";
	
	public static final String _DEFAULT_ACTOR = _SWITCH_ACTOR;
	
	public static final String _SHELL_EXECUTOR = "objShell.ShellExecute";
	
	public static final String _SECURE_CRT = "\"SecureCRT.EXE\",";
	
	public static final String _CRT_ARG = "/SCRIPT";
	
	public static final String _BLANK = " ";
	
	public static final String _AND = " & ";
}
