package com.bdcom.util.log;

import com.bdcom.service.Application;
import com.bdcom.service.ConfigPath;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.util.Date;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2012-12-11 <br>
 * Auto-Generated by eclipse Juno <br>
 */

public abstract class MsgLogger {

    private static final String _SPT = ConfigPath._SPT;
	
	private static final String CURRENT_DIR = Application.CURRENT_DIR;
	
	private static final DateFormat DATE_FORMAT = Application.DATE_FORMAT;
	
	private static final String LOG_DIR = _SPT+"log"+_SPT+"msg"+_SPT;
	
	private static final String _END_FIX = ".log.txt";
	
	private static String LOG_FILE_NAME;
	
	private static File logFile;
	
	private static boolean logCreateSuccess;
	
	static {
		LOG_FILE_NAME = DATE_FORMAT.format( new Date() );
		logFile = new File(getPathToSave() + LOG_FILE_NAME + _END_FIX);
		if (!logFile.exists()) {
			try {
				if ( logFile.createNewFile() ) {
					logCreateSuccess = true;
				} else {
					logCreateSuccess = false;
				}
			} catch (IOException e) {
				System.err.println(e.getMessage());
			}
		} else {
			logCreateSuccess = true;
		}
	}
	
	public static void log(String msg) {
		if (!logCreateSuccess) {
			return;
		}
		FileWriter fw;
		try {
			fw = new FileWriter(logFile, true);
			BufferedWriter bw = new BufferedWriter(fw);
			bw.write(msg);
			bw.newLine();
			bw.flush();
			bw.close();
			fw.close();
		} catch (IOException e) {
		}
	}
	
	private static String getPathToSave() {
		StringBuffer sb = new StringBuffer();
		sb.append(CURRENT_DIR)
		  .append(LOG_DIR);
		File sceDir = new File(sb.toString());
		if ( !sceDir.exists() ) {
			sceDir.mkdirs();
		}
		
		return sb.toString();
	}
}
