package com.bdcom.clientview.util;



/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2012-11-22 <br>
 * Auto-Generated by eclipse Juno <br>
 */

public interface Messages {
	
	public static final String BLANK_USR_NAME = 
			"username can't be blank!";
	
	public static final String BLANK_PASSWD = 
			"password can't be blank!";
	
	public static final String _NOT_DONE_YET_S = 
			"operation not done, try later!";
	
	public static final String _SUCCESS_S = 
			"submit success!";
	
	public static final String _FAIL_S = 
			"submit fail!";
	
	public static final String _SCRIPT_MODIFY_SUCCESS_S =
			"script modify success";
	
	public static final String _SCRIPT_REMOVE_SUCCESS_S =
			"script remove success";
	
	public static final String _SCRIPT_ADDED_SUCCESS_S =
			"script added success";
	
	public static final String _AUTH_FAIL_S = 
			"authentication fail!";
	
	public static final String _TIME_OUT_S = 
			"request timeout!";
	
	public static final String _LOCAL_INTERNAL_ERROR_S =
			"application inner error!";
	
	public static final String _SERVER_INIT_FAILURE_S =
			"server initialise fail!";
	
	public static final String _SERVER_IO_FAILURE_S =
			"server ocurrs IO error!";
	
	public static final String _INVAILD_DATA_S =
			"data format is invaild!";
	
	public static final String _INVAILD_PATH_S =
			"file path is invaild!";
	
	public static final String _SCRIPT_CONF_NOT_FOUND_S = 
			"default script config file not found!";
	
	public static final String _NO_MATCHED_SCRIPT_S =
			"no matched script!";
	
	public static final String _SCRIPT_EXECUTION_FAIL_S =
			"script execution fail!";
	
	public static final String _SCRIPT_FILE_NOT_FOUND_S =
			"can't find matched script file!";
	
	public static final String _SCRIPT_SERIAL_REDUPLICATED_S = 
			"script serial reduplicated!";
	
	public static final String _SCRIPT_PARSE_ERROR_S =
			"script parse error!";
	
	public static final String _SCRIPT_CONF_FILE_CREATE_FAIL_S =
			"script config file create fail!";
	
	public static final String SCRIPT_CONF_FILE_SAVE_FAIL_S =
			"script config file  save fail!";
	
	public static final String _DIR_CREATE_FAIL_S =
			"directory create fail!";
	
	public static final String _DIR_SAVE_SUCCESS_S =
			"save success!";
	
	public static final String _DIR_NOT_EXSIT_S =
			"path not exsit!";
	
	public static final String _IS_FILE_NOT_DIR_S =
			"is file not dir!";
	
	public static final String _CONF_FILE_CREATE_FAIL_S =
			"conf file create fail!";
	
	public static final String _SYNC_SUCCESS_S =
			"sync success!";
	
	public static final String _SYNC_FAIL_S = 
			"sync fail!";
	
	public static final String _SUCCESS_INVALID_S =
			"send success, but no more test!";
	
	public static final String _SUCCESS_ADD_FAIL_S = 
			"send success, but fail to add to db!";
	
	public static final String _SUCCESS_PASS_S = 
			"send success, and test passed!";
	
	public static final String _SUCCESS_UNPASS_S = 
			"send success, and test unpassed!";
	
	public static final String _SERVER_CONNEC_FAIL_S =
			"server connecting failure!";
	
	public static final String _LOCAL_LOGOUT_S = 
			"has logout";
	
	public static final String EXE_DONE_S =
			"execution finished";
	
	public static final String INVALID_CLIENT_VERSION_S = 
			"Client version is too low, please update to latest version";
}
