package com.bdcom.clientview.util;

import com.bdcom.service.Application;
import com.bdcom.service.ApplicationConstants;
import com.bdcom.util.LocaleUtil;

import javax.swing.*;
import java.awt.*;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2012-11-28 <br>
 * Auto-Generated by eclipse Juno <br>
 */

public abstract class MsgDialogUtil implements ApplicationConstants {
	
	public static void showErrorDialog(String msg) {
        JComponent current = (JComponent) Application.getCurrentDisplay();
		showDialog( current,
				msg, _ERROR, JOptionPane.ERROR_MESSAGE);
	}
	
	public static void showErrorDialog(Component compo, String msg) {
		showDialog(compo, msg, _ERROR, JOptionPane.ERROR_MESSAGE);
	}
	
	public static void showErrorDialogLocalised(String msg) {
		showErrorDialog(
				LocaleUtil.getLocalName(msg)
				);
	}
	
	public static void showErrorDialogLocalised(Component compo, String msg) {
		showErrorDialog(
				compo,
				LocaleUtil.getLocalName(msg)
				);
	}
	
	public static void showMsgDialog(String msg) {
        JComponent current = (JComponent) Application.getCurrentDisplay();
		showDialog( current,
				msg, _MESSAGE, JOptionPane.INFORMATION_MESSAGE);
	}
	
	public static void showMsgDialog(Component compo, String msg) {
		showDialog(compo, 
				msg, _MESSAGE, JOptionPane.INFORMATION_MESSAGE);
	}
	
	public static void showMsgDialogLocalised(String msg) {
		showMsgDialog(
				LocaleUtil.getLocalName(msg)
				);
	}
	
	public static void showMsgDialogLocalised(Component compo,String msg) {
		showMsgDialog(
				compo,
				LocaleUtil.getLocalName(msg)
				);
	}
	
	private static void showDialog(Component compo, String msg, String msgType, int dialogType) {
		JOptionPane.showMessageDialog(
                compo,
				msg,
				LocaleUtil.getLocalName(msgType),
				dialogType);
	}
}
