package com.bdcom.view.util;

import java.awt.GridBagConstraints;
import java.awt.Insets;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2012-11-15 <br>
 * Auto-Generated by eclipse Juno <br>
 */

public class GBC extends GridBagConstraints {  
	
	private static final long serialVersionUID = -1367297493550098226L;

	public GBC(int gridx, int gridy) {
	    this.gridx = gridx;  
	    this.gridy = gridy;  
	 }  
	  
	public GBC(int gridx, int gridy, int gridwidth, int gridheight) {
	     this.gridx = gridx;  
	     this.gridy = gridy;  
	     this.gridwidth = gridwidth;  
	     this.gridheight = gridheight;  
	 }  
	   
	 public GBC setGridwidth(int gridwidth) {
		  this.gridwidth = gridwidth;
		  return this;
	 }
	   
	 public GBC setGridheight(int gridheight) {
		  this.gridwidth = gridheight;
		  return this;
	 }
	  
	 public GBC setAnchor(int anchor) {
	      this.anchor = anchor;  
	      return this;  
	  }  
	  
	 public GBC setFill(int fill) {
	      this.fill = fill;  
	      return this;  
	  }  
	  
	 public GBC setWeight(double weightx, double weighty) {
	      this.weightx = weightx;
	      this.weighty = weighty;  
	      return this;  
	  }  
	  
	 public GBC setInsets(int distance) {
	      this.insets = new Insets(distance, distance, distance, distance);  
	      return this;  
	  }  
	  
	 public GBC setInsets(int top, int left, int bottom, int right) {
	      this.insets = new Insets(top, left, bottom, right);  
	      return this;  
	  }  
	  
	  public GBC setIpad(int ipadx, int ipady) {
	      this.ipadx = ipadx;  
	      this.ipady = ipady;  
	      return this;  
	   }  
	   
	  public GBC setIpadx(int ipadx) {  
	      this.ipadx = ipadx;  
	      return this;  
	   }  
	   
	  public GBC setIpady(int ipady) {  
	      this.ipady = ipady;  
	      return this;  
	   }  
	   
}  