package com.bdcom.dce.util;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2012-11-20 <br>
 * Auto-Generated by eclipse Juno <br>
 */

public interface CommunicateStatus {
	
	public static final int _NOT_DONE_YET = 0;
	
	public static final int _LOCAL_LOGOUT = 1;
	
	public static final int EXE_DONE = 2;
	
	public static final int NO_RUNNING_SCRIPT = 3;
	
	public static final int _SUCCESS_INVALID = 886;
	
	public static final int _SUCCESS_ADD_FAIL = 887;

	public static final int _SUCCESS = 888;
	
	public static final int _SUCCESS_PASS = 889;
	
	public static final int _SUCCESS_UNPASS = 890;
	
	public static final int _SCRIPT_ADDED_SUCCESS = 666;
	
	public static final int _INTERPRETER_ADD_SUCCESS = _SCRIPT_ADDED_SUCCESS;
	
	public static final int _CRT_SESSION_ADD_SUCCESS = _SCRIPT_ADDED_SUCCESS;
	
	public static final int _SCRIPT_MODIFY_SUCCESS = 555; 
	
	public static final int _SCRIPT_REMOVE_SUCCESS = 111;
	
	public static final int _DIR_SAVE_SUCCESS = 222;
	
	public static final int _SYNC_SUCCESS = 333;
	
	public static final int _FAIL = -1;
	
	public static final int _TIME_OUT = -2;
	
	public static final int _AUTH_FAIL = -3;
	
	public static final int _LOCAL_INTERNAL_ERROR = -4;
	
	public static final int _SYNC_FAIL = -5;
	
	public static final int _SERVER_INIT_FAILURE = -11;
	
	public static final int _SERVER_IO_FAILURE = -12;
	
	public static final int _SERVER_CONNEC_FAIL = -13;
	
	public static final int _INVAILD_DATA = -30;
	
	public static final int _INVAILD_PATH = -31;
	
	public static final int _SCRIPT_CONF_NOT_FOUND = -40;
	
	public static final int _NO_MATCHED_SCRIPT = -41;
	
	public static final int _SCRIPT_EXECUTION_FAIL = -42;
	
	public static final int _SCRIPT_FILE_NOT_FOUND = -43;
	
	public static final int _SCRIPT_SERIAL_REDUPLICATED = -44;
	
	public static final int _SCRIPT_CONF_FILE_CREATE_FAIL = -45;
	
	public static final int SCRIPT_CONF_FILE_SAVE_FAIL = -46;
	
	public static final int _SCRIPT_PARSE_ERROR = -47;
	
	public static final int _DIR_CREATE_FAIL = -50;
	
	public static final int _DIR_NOT_EXSIT = -51;
	
	public static final int _IS_FILE_NOT_DIR = -52;
	
	public static final int _CONF_FILE_CREATE_FAIL = -53;
	
	public static final int INVALID_CLIENT_VERSION = -100;
}
