package com.bdcom.dce.biz.script.interpreter;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2012-11-30 <br>
 * Auto-Generated by eclipse Juno <br>
 */

public interface DefaultInterpreters {
	
	public static final String DL_CRT = "Download";

	public static final String TT_CRT = "Telnet";
	
	public static final String RT_CRT = "Router";
	
	public static final String EO_CRT = "EponOnu";
	
}
