package socket.test;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2012-10-31 <br>
 * Auto-Generated by eclipse Juno <br>
 */

public interface CommuniConstants {
	
	public static final String AUTH_SUCCESS = "$$";
	
	public static final String AUTH_FAIL = "^^";
	
	public static final String SCE_FLAG = "@#";
	
	public static final String SESSION_SPT = "%%";
	
	public static final String SEPARATOR = "##";
	
	public static final String END_FLAG = "@@";
	
	public static final String INVAID_DATA = "((((";
	
	public static final String TERMINAL_FLAG = "))))";
	
	public static final String TERMINAL_NOLOGOUT_FLAG = ">>>>";
	
	public static final String TESTER_ID = "testerNum";
	
	public static final String TEST_TYPE = "type";
	
	public static final String BEGIN_TIME = "beginTime";
	
	public static final String SCRIPT = "script";
	
	public static final String TERMINAL_NAME = "consoleName";
	
	public static final String SERIAL_NO = "serialNumber";
	
	public static final String SUB_STRATE_NO = "id";
	
	public static final String EPROM_VER= "verOfEPROM";
	
	public static final String FLASH_ROOM= "volOfFlash";
	
	public static final String SDRA_ROOM= "volOfDRam";
	
	public static final String SOFTWARE_INFO = "softwareInfo";
	
	public static final String HARDWARE_INFO = "hardwareInfo";
	
	public static final String VERSION = "modelType";
	
	public static final String END_TIME = "endTime";
	
	public static final String IS_PASS = "status";
	
	public static final String[] ENTITY_FIELDS = {
		TESTER_ID, TEST_TYPE, BEGIN_TIME,
		SCRIPT, TERMINAL_NAME, SERIAL_NO,
		SUB_STRATE_NO, EPROM_VER, FLASH_ROOM, 
		SDRA_ROOM, SOFTWARE_INFO, HARDWARE_INFO,
		VERSION, END_TIME, IS_PASS
	};
	
}
