package socket.test;

import java.util.concurrent.TimeUnit;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2012-11-1<br>
 * Auto-Generated by eclipse Juno <br>
 */

public class TestCase {
	public static void main(String[] args) {
		DataAchieverDaemon dataAchieverDaemon = new DataAchieverDaemon(Integer.parseInt("5768"));
		dataAchieverDaemon.setDataSaver(null);
		
		Thread daemonThread = new Thread(dataAchieverDaemon);
		daemonThread.setDaemon(true);
		daemonThread.start();
		while (true) {
			try {
				TimeUnit.SECONDS.sleep(5);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		}
	}
}
