package com.bdcom.dce.view;

import java.awt.Component;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2012-11-28 <br>
 * Auto-Generated by eclipse Juno <br>
 */

public interface AbstractFrame {
	
	public void display();
	
	public void hideFrame();
	
	public Component getSelfFrame();
	
	public void refresh();
}
