package com.bdcom.dce.sys.configure;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2012-11-28 <br>
 * Auto-Generated by eclipse Juno <br>
 */

public interface ServerInfoConstants {
	
	public static final String _SERVER = "server";
	
	public static final String _IP = "ip";
	
	public static final String _PORT = "port";
			
	public static final String _HOST = "host";
	
	public static final String DEFAULT_IP = "127.0.0.1";
	
	public static final String DEFAULT_PORT = "9999";
	
	public static final String DEFAULT_HOST = "localhost";
			
}
