package com.bdcom.dce.view.util;

import static com.bdcom.dce.util.CommunicateStatus.*;
import static com.bdcom.dce.view.util.Messages.*;

import java.util.HashMap;
import java.util.Map;

import com.bdcom.dce.util.LocaleUtil;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2012-11-22 <br>
 * Auto-Generated by eclipse Juno <br>
 */

public abstract class MessageUtil {
			
	public static Map<Integer, String> msgContainer = 
			new HashMap<Integer, String>();
	
	static {
		msgContainer.put(new Integer(_NOT_DONE_YET), _NOT_DONE_YET_S );
		msgContainer.put(new Integer(_SUCCESS), _SUCCESS_S);
		msgContainer.put(new Integer(_FAIL), _FAIL_S);
		msgContainer.put(new Integer(_TIME_OUT), _TIME_OUT_S);
		msgContainer.put(new Integer(_LOCAL_INTERNAL_ERROR), _LOCAL_INTERNAL_ERROR_S);
		msgContainer.put(new Integer(_SERVER_INIT_FAILURE), _SERVER_INIT_FAILURE_S);
		msgContainer.put(new Integer(_SERVER_IO_FAILURE), _SERVER_IO_FAILURE_S);
		msgContainer.put(new Integer(_AUTH_FAIL), _AUTH_FAIL_S);
		msgContainer.put(new Integer(_INVAILD_DATA), _INVAILD_DATA_S);
		msgContainer.put(new Integer(_INVAILD_PATH), _INVAILD_PATH_S);
		msgContainer.put(new Integer(_SCRIPT_CONF_NOT_FOUND), _SCRIPT_CONF_NOT_FOUND_S);
		msgContainer.put(new Integer(_NO_MATCHED_SCRIPT), _NO_MATCHED_SCRIPT_S);
		msgContainer.put(new Integer(_SCRIPT_EXECUTION_FAIL), _SCRIPT_EXECUTION_FAIL_S);
		msgContainer.put(new Integer(_SCRIPT_FILE_NOT_FOUND), _SCRIPT_FILE_NOT_FOUND_S);
		msgContainer.put(new Integer(_SCRIPT_SERIAL_REDUPLICATED), _SCRIPT_SERIAL_REDUPLICATED_S);
		msgContainer.put(new Integer(_SCRIPT_PARSE_ERROR), _SCRIPT_PARSE_ERROR_S);
		msgContainer.put(new Integer(_SCRIPT_CONF_FILE_CREATE_FAIL), _SCRIPT_CONF_FILE_CREATE_FAIL_S);
		msgContainer.put(new Integer(SCRIPT_CONF_FILE_SAVE_FAIL), SCRIPT_CONF_FILE_SAVE_FAIL_S);
		msgContainer.put(new Integer(_DIR_CREATE_FAIL), _DIR_CREATE_FAIL_S);
		msgContainer.put(new Integer(_DIR_SAVE_SUCCESS), _DIR_SAVE_SUCCESS_S);
		msgContainer.put(new Integer(_SCRIPT_MODIFY_SUCCESS), _SCRIPT_MODIFY_SUCCESS_S);
		msgContainer.put(new Integer(_SCRIPT_REMOVE_SUCCESS), _SCRIPT_REMOVE_SUCCESS_S);
		msgContainer.put(new Integer(_SCRIPT_ADDED_SUCCESS), _SCRIPT_ADDED_SUCCESS_S);
		msgContainer.put(new Integer(_DIR_NOT_EXSIT), _DIR_NOT_EXSIT_S);
		msgContainer.put(new Integer(_IS_FILE_NOT_DIR), _IS_FILE_NOT_DIR_S);
		msgContainer.put(new Integer(_CONF_FILE_CREATE_FAIL), _CONF_FILE_CREATE_FAIL_S);
		msgContainer.put(new Integer(_SYNC_SUCCESS), _SYNC_SUCCESS_S);
		msgContainer.put(new Integer(_SYNC_FAIL), _SYNC_FAIL_S);
		msgContainer.put(new Integer(_SUCCESS_INVALID), _SUCCESS_INVALID_S);
		msgContainer.put(new Integer(_SUCCESS_ADD_FAIL), _SUCCESS_ADD_FAIL_S);
		msgContainer.put(new Integer(_SUCCESS_PASS), _SUCCESS_PASS_S);
		msgContainer.put(new Integer(_SUCCESS_UNPASS), _SUCCESS_UNPASS_S);
		msgContainer.put(new Integer(_SERVER_CONNEC_FAIL), _SERVER_CONNEC_FAIL_S);
		msgContainer.put(new Integer(_LOCAL_LOGOUT), _LOCAL_LOGOUT_S);
		msgContainer.put(new Integer(EXE_DONE), EXE_DONE_S);
		msgContainer.put(new Integer(INVALID_CLIENT_VERSION), INVALID_CLIENT_VERSION_S);
	}
	
	public static String getLocalisedMessage(String msg) {
		return LocaleUtil.getLocalName(msg);
	}
	
	public static String getMessageByStatusCode(int status) {
		return LocaleUtil.getLocalName(
				msgContainer.get(new Integer(status))
				);
	}
}
