package com.bdcom.biz.script.session;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2012-12-10 <br>
 * Auto-Generated by eclipse Juno <br>
 */

public interface DefaultCrtSessions {
	
	public static final String DL_CRT = "Download";

	public static final String TT_CRT = "Telnet";
	
	public static final String RT_CRT = "Router";
	
	public static final String EO_CRT = "EponOnu";
	
}
