package com.bdcom.dce.datadispacher;


/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2012-11-22 <br>
 * Auto-Generated by eclipse Juno <br>
 */

public interface CommuniConstants {
	
	public static final String AUTH_SUCCESS = "$$";
	
	public static final String INVALID_VER_MSG = "^<";
	
	public static final String AUTH_FAIL = "^^";
	
	public static final String SCE_FLAG = "@#";
	
	public static final String SESSION_SPT = "%%";
	
	public static final String SEPARATOR = "##";
	
	public static final String END_FLAG = "@@";
	
	public static final String INVAID_DATA = "((((";
	
	public static final String TERMINAL_FLAG = "))))";
	
	public static final String TERMINAL_NOLOGOUT_FLAG = ">>>>";
	
	public static final String SYNC_FLAG = "~~~~";
	
	public static final String UPLOAD_FLAG = "AA";
	
	public static final String DOWNLOAD_FLAG = "VV";
}
