package socket.test.ext;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2012-12-12 <br>
 * Auto-Generated by eclipse Juno <br>
 */

public interface ISmtFactory {

}
