package com.bdcom.dce.biz.pojo;

import java.io.Serializable;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.Map.Entry;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2012-11-14 <br>
 * Auto-Generated by eclipse Juno <br>
 */

public class Scenario implements Serializable {
	
	private static final long serialVersionUID = 458346062352593578L;
    public static final DateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd-HH:mm:ss");

	private static long _maxId = -1; //can't Serialize, should int by hand
	
	private long id = -1;
	
	private int beginIndex = -1;

	private String scenarioName;
	
	private String serialNum;

    private final Date dateCreate;

    private Date dateModify;

	private Map<String, String> restrictAttr = new HashMap<String, String>();

    public Scenario() {
        dateCreate = new Date();
    }

    public Date getDateCreate() {
        return dateCreate;
    }

    public Date getDateModify() {
        return dateModify;
    }

    public String getFormattedCreateDate() {
        return DATE_FORMAT.format( dateCreate );
    }

    public String getFormattedModifyDate() {
        return DATE_FORMAT.format( dateModify );
    }

    public String getScenarioName() {
		return scenarioName;
	}

	public void setScenarioName(String scenarioName) {
		this.scenarioName = scenarioName;
	}
	
	public String getSerialNum() {
		return serialNum;
	}

	public void setSerialNum(String serialNum) {
        updateDateModify();
		this.serialNum = serialNum;
	}

	public int getBeginIndex() {
		return beginIndex;
	}

	public void setBeginIndex(int beginIndex) {
        updateDateModify();
		this.beginIndex = beginIndex;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}
	
	public void idAutoIncrease() {
		_maxId ++;
		id = _maxId;
	}

	public static long getMaxId() {
		return _maxId;
	}

	public static void setMaxId(long maxId) {
		_maxId = maxId;
	}
	
	public static void calcMaxId(Collection<Scenario> collec) {
		if ( null != collec && !collec.isEmpty() ) {
			long maxId = -1;
			for ( Scenario sce : collec ) {
				long id = sce.getId();
				if ( maxId < id) {
					maxId = id;
				}
			}
			_maxId = maxId;
		}
	}

	public void setRestrictAttr(Map<String, String> attrs) {
        updateDateModify();
		restrictAttr = attrs;
	}

	public void putAttr(String attrName, String attrValue) {
        updateDateModify();
		restrictAttr.put(attrName, attrValue);
	}
	
	public String getAttr(String attrName) {
		return restrictAttr.get(attrName);
	}
	
	public Set<String> getAttrNames() {
		return restrictAttr.keySet();
	}
	
	public void rmAttr(String attrName) {
        updateDateModify();
		restrictAttr.remove(attrName);
	}
	
	public boolean isNoAttrAdded() {
		return restrictAttr.isEmpty();
	}
	
	public void clearAllAttr() {
        updateDateModify();
		restrictAttr.clear();
	}

    private void updateDateModify() {
        dateModify = new Date();
    }
	
	public long getHashCode() {
		long h = 0;
		long t = 1;
		if ( null == restrictAttr ||
				restrictAttr.isEmpty() ) {
			return 0;
		} else {
			for ( Entry<String, String> entry : restrictAttr.entrySet() ) {
				for ( int i=0; i< restrictAttr.size(); i++ ) {
					t += t*2 + entry.getKey().length()*3 + 
							entry.getValue().hashCode()*2;
					h += t;
				}
			}
		}
		
		if ( h < 0 ) {
			h = -h;
		}
		String hs = String.valueOf(h);
		if ( hs.length() > 10) {
			String ps = hs.substring(hs.length()- 10, hs.length());
			while ( ps.startsWith("0")) {
				ps = ps.substring(1, ps.length());
			}
			return Long.parseLong(ps);
		}
		return h;
	}
	
}
