package com.bdcom.util;

import java.util.Locale;
import java.util.ResourceBundle;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2012-11-15 <br>
 * Auto-Generated by eclipse Juno <br>
 */

public abstract class LocaleUtil {
	
	private static Locale zhLoc;
	
	private static ResourceBundle zhrb;
	
	static {
		zhLoc = new Locale("zh", "CN");
		zhrb = ResourceBundle.getBundle("Locale",zhLoc);
	}
	
	public static String getLocalName(String name) {
		return zhrb.getString(name);
	}
	
	public static String getOriginalName(String name) {
		//Not Done yet
		return name;
	}
}
