package com.bdcom.biz.script.interpreter;

import com.bdcom.biz.script.ScriptXmlConfConstants;
import com.bdcom.util.StringUtil;

import java.io.IOException;

/**
 * @author francis yuan <br>
 * E-mail: yuanjiajun@bdcom.com.cn <br>
 * @version 2012-11-30 <br>
 * Auto-Generated by eclipse Juno <br>
 */

public class ScriptInterpreter implements ScriptXmlConfConstants {
	
	private Process process;
	
	private ScriptInteractor scriptInteractor;
	
	private String interpreter;
	
	private String interpreterPath;
	
	private boolean isRunning = false;
	
	public ScriptInteractor getScriptInteractor() {
		return scriptInteractor;
	}

	public void setScriptInteractor(ScriptInteractor scriptInteractor) {
		this.scriptInteractor = scriptInteractor;
	}

	public String getInterpreter() {
		return interpreter;
	}
	
	public void setInterpreter(String interpreter) {
		this.interpreter = interpreter;
	}
	
	public String getInterpreterPath() {
		return interpreterPath;
	}
	
	public void setInterpreterPath(String interpreterPath) {
		this.interpreterPath = interpreterPath;
	}
	
	public Process getProcess() {
		return process;
	}
	
	public void runScript(String scriptPath) throws IOException, InterruptedException {
		String cmd = getCmd(interpreterPath, interpreter, scriptPath);
		System.out.println(cmd);
		if ( isRunning ) {
			killInterpreterProcess();
		}
		
		if ( StringUtil.isNotBlank(cmd) ) {
			isRunning = true;
			process = Runtime.getRuntime().exec(cmd);
		}
		if ( null != scriptInteractor && null != process ) {
			scriptInteractor.interact(process);
		}
	}
	
	public void killInterpreterProcess() {
		if ( null != process ) {
			isRunning = false;
			process.destroy();
		}
	}
	
//		public static void main(String[] args) {
//			System.out.println(
//					getCmd("c:\\hello\\", "/S router", "e:\\hello\\hello\\hello.vbs")
//					);
//		}
		
	public static String getCmd(String interpreterPath, String interpreter, String scriptPath) {
		StringBuffer sb = new StringBuffer();
		
//		String scriptDir = null;
//		String scriptName = null;
//		if ( StringUtil.isNotBlank(scriptPath) ) {
//			int spt = scriptPath.lastIndexOf("\\"); 
//			scriptDir = scriptPath.substring(0, spt);
//			scriptName  = scriptPath.substring(spt+1);
//		}
		
		if (StringUtil.isNotBlank(interpreterPath) 
				&& StringUtil.isNotBlank(scriptPath) ) {
			sb.append(interpreterPath)
			  .append(_BLANK)
			  .append(_CRT_ARG)
			  .append(_BLANK)
			  .append(scriptPath)
			  .append(_BLANK)
			  .append("/S")
			  .append(_BLANK)
			  .append(interpreter);
		}
		
//		if ( StringUtil.isNotBlank(interpreterPath) &&
//				StringUtil.isNotBlank(interpreter) ) {
//			if ( interpreterPath.endsWith("\\") ) {
//				sb.append(interpreterPath).append(interpreter);
//			} else {
//				sb.append(interpreterPath).append("\\")
//				.append(interpreter);
//			}
//			File testFile = new File(sb.toString());
//			if ( !testFile.exists() ) {
//				return scriptPath;
//			}
//		}
//		
//		
//		if ( StringUtil.isNotBlank(scriptPath) ) {
//			if ( sb.length() > 0) {
//				sb.append(" ").append(scriptPath);
//			} else {
//				sb.append(scriptPath);
//			}
//		} else {
//			return "";
//		}
		
		return sb.toString();
	}
	
//	public void runScript(String scriptPath) throws IOException, InterruptedException {
//		process = Runtime.getRuntime().exec(scriptPath);
//		InputStream in = process.getInputStream();
//		BufferedReader br = new BufferedReader(new InputStreamReader(in));
//		System.out.println(br.readLine());
//		long ms = System.currentTimeMillis();
//		process.waitFor();
//		ms = System.currentTimeMillis() - ms;
//		System.out.println("process run time: " + ms );
//	}
//	
//	public static void main(String[] args) {
//		String script = "E:\\easework\\DataDispenseClient\\scritps\\hello.bat";
//		final ScriptInterpreter si = new ScriptInterpreter();
//		Runnable waitingThread = new Runnable() {
//			@Override
//			public void run() {
//				int i = 0;
//				while ( true ) {
//					try {
//						TimeUnit.MILLISECONDS.sleep(100);
//					} catch (InterruptedException e) {
//					};
//					System.out.print(i + ", ");
//					
//					if ( i >= 20) {
//						System.out.println();
//						break;
//					}
//					i++;
//				}
//				si.killInterpreterProcess();
//			}
//		};
//		
//		new Thread(waitingThread).start();
//		try {
//			si.runScript(script);
//		} catch (IOException e) {
//			e.printStackTrace();
//		} catch (InterruptedException e) {
//			e.printStackTrace();
//		}
//		
//	}
	
}
